version: '3.8'

services:
  postgres_test:
    image: postgres:15
    container_name: everything_app_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: everything_app_test
    ports:
      - "5433:5432"  # Use a different port to avoid conflicts with dev database
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
